# Generated by Django 5.2 on 2025-04-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pattern', models.CharField(max_length=100)),
                ('progress_status', models.CharField(choices=[('planned', 'Planned'), ('in-progress', 'In-Progress'), ('complete', 'Complete')], default='Planned')),
            ],
        ),
    ]
