# Generated by Django 5.2 on 2025-04-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_project_cast_off_project_cast_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='needle_size',
            field=models.CharField(choices=[('00000', '1.0mm US 00000'), ('0000', '1.25mm US 0000'), ('000', '1.5mm US 000'), ('00', '1.75mm US 00'), ('0', '2mm US 0'), ('1', '2.25mm US 1'), ('1.5', '2.5mm US 1.5'), ('2', '2.75mm US 2'), ('2.5', '3mm US 2.5'), ('3', '3.25mm US 3'), ('4', '3.5mm US 4'), ('5', '3.75mm US 5'), ('6', '4.0mm US 6'), ('7', '4.5mm US 7'), ('8', '5mm US 8'), ('9', '5.5mm US 9'), ('10', '6mm US 10'), ('10.5', '6.5mm US 10.5'), ('11', '8mm US 11'), ('13', '9mm US 13'), ('14', '9.5mm US 14'), ('15', '10mm US 15'), ('17', '12mm US 17'), ('19', '16mm US 19'), ('35', '19mm US 35'), ('50', '25mm US 50')], default='7'),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress_status',
            field=models.CharField(choices=[('P', 'Planned'), ('IP', 'In-Progress'), ('C', 'Complete')], default='P'),
        ),
    ]
