# Generated by Django 5.2 on 2025-04-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_notes_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yarn_name', models.CharField(max_length=100)),
                ('yarn_weight', models.CharField(choices=[('0', '0 Lace'), ('1', '1 Super Fine'), ('2', '2 Fine'), ('3', '3 Light'), ('4', '4 Medium'), ('5', '5 Bulky'), ('6', '6 Super Bulky'), ('7', '7 Jumbo')], default='4')),
                ('fiber_type', models.CharField()),
                ('color', models.CharField(max_length=100)),
                ('yarn_quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(verbose_name='Knitting Session Date'),
        ),
    ]
