# Generated by Django 5.2 on 2025-04-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_yarn_alter_note_options_alter_note_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='yarn',
            field=models.ManyToManyField(to='main_app.yarn'),
        ),
    ]
